# Generated by Django 3.2.9 on 2021-12-05 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RouteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stepnum', models.IntegerField()),
                ('stationName', models.CharField(max_length=30)),
                ('gcj02_longi', models.FloatField()),
                ('gcj02_lati', models.FloatField()),
                ('wgs84_longi', models.FloatField()),
                ('wgs84_lati', models.FloatField()),
                ('lineName', models.CharField(max_length=30)),
                ('lineType', models.CharField(choices=[('bus', 'bus'), ('subway', 'subway')], max_length=20)),
                ('FTW', models.CharField(max_length=80)),
            ],
        ),
    ]
