# Generated by Django 3.2.9 on 2021-12-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route_plan', '0002_routeinfo_stationhallmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='routeinfo',
            name='w_cost',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='routeinfo',
            name='w_dist',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='routeinfo',
            name='w_time',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
